### ISSUE TITLE
Consider recommendation of pattern `not x == y`?

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/rego-style-guide#16]
I've seen this pattern in many policies out in the "wild": 

```rego
package policy

deny["input.foo must be true"] {
    not input.foo == true
}
```

Compared to using `input.foo != true`, this pattern also handles the undefined case, and as such extends the recommendation to [use negation to handle undefined](https://github.com/StyraInc/rego-style-guide#use-negation-to-handle-undefined).

The question is whether we should include this as a general recommendation, perhaps just as an example included in the current recommendation? 🤔

Where things tend to get complicated, is when using "double negation" like `not input.foo != true` ... and I don't think that's something I'd like to read myself 😅 But granted that `not` + equality works without caveats, perhaps it should be preferred over `!=`?

**Comment by anderseknert** [comment]
As pointed out by @srenatus , the pattern breaks for cases where both sides of the equation are undefinded:
```rego
deny["input.foo must not be equal to input.bar"] {
    not input.foo == input.bar
}
```
The `not` would evaluate to `true` in this case, which is unlikely to be intended. Still, comparing to a constant, or "known" defined value, might be preferable over a separate check for undefined + not equals comparison.

**Comment by ericjkao** [comment]
Wow this is a tough one. My two cents in a few thoughts:
1. I don't see a reason make a general recommendation of using one form over another; it comes down to what behavior the author wants in the case of undefined. `deny if not input.is_admin == true` may be good, but `allow if not input.is_admin == false` may be bad. It all depends on the desired behavior and contract with the caller of OPA.  
2. In the case that someone wants the condition to succeed if one side is undefined, `not .. == ..` seems like a reasonable way to go.
3. It may cause people to do things like `not input.foo >= 1`, which fails when one side is undefined. But @philipaconrad is working on hopefully evolving this behavior.
4. I do not see a problem with `not input.foo == input.bar` succeeding when both sides are undefined. `undefined == undefined` evaluating to undefined is consistent with SQL where `NULL = NULL` evaluates to "unknown". Then as long as one understands that `not` means `is_false_or_undefined` (different from SQL), the success of `not input.foo == input.bar` makes sense. If there is a problem, it is because the keyword is called `not` rather than something else that alerts people to the behavior in case of undefined.

**Comment by anderseknert** [comment]
Thanks @ericjkao! I appreciate your input, and I think we have enough to conclude that a general recommendation isn't needed here. Closing the issue, but hopefully people can still find it in case they want to know more about how the pattern works, and possible gotchas.
